apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secret
  labels:
    app: todo-app
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=      # "postgres" в base64
  DB_PASSWORD: cG9zdGdyZXM=      # "postgres" в base64
  DB_NAME: dG9kbw==              # "todo" в base64
