# === Этап 1. Сборка jar внутри контейнера (builder) ===
FROM maven:3.9-eclipse-temurin-17-alpine AS builder

# Рабочая папка внутри контейнера
WORKDIR /app

# Сначала копируем pom.xml и скачиваем зависимости (кэшируется)
COPY pom.xml .
RUN mvn -q dependency:go-offline

# Потом копируем исходный код
COPY src ./src

# Собираем jar (получим target/todo-app.jar)
RUN mvn -q clean package -DskipTests

# === Этап 2. Лёгкий образ только с JDK и jar ===
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

# Копируем jar из первого этапа
COPY --from=builder /app/target/todo-app.jar app.jar

# Как запускаем приложение
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
