FROM maven:3.9-eclipse-temurin-17-alpine AS builder

WORKDIR /app

COPY pom.xml .
RUN mvn -q dependency:go-offline

COPY src ./src

# Собираем jar (получим target/todo-app.jar)
RUN mvn -q clean package -DskipTests

FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app


COPY --from=builder /app/target/todo-app.jar app.jar

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
